version: '3.9'
services:
    
    psql:
        image: postgres:13.2
        restart: unless-stopped
        environment:
            POSTGRES_USER: ory-user
            POSTGRES_PASSWORD: ory-pass
            POSTGRES_DB: ory-data
        ports:
            - 5432:5432
        #     PGDATA: /mnt/data/psql/data
        #     POSTGRES_INITDB_WALDIR: /mnt/data/psql/wal
        # volumes:
        #     -
        #         type: bind
        #         source: ./psql/data
        #         target: /mnt/data/psql/data
        #     -
        #         type: bind
        #         source: ./psql/wal
        #         target: /mnt/data/psql/wal
        networks:
            - ory

    hydra-migrate:
        depends_on:
            - psql
        image: ory-hydra:v1.10.3
        restart: on-failure
        command:
            migrate -c /etc/config/hydra/hydra.yml sql -e --yes
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
        volumes:
            -
                type: bind
                source: ./configs/hydra
                target: /etc/config/hydra
        networks:
            - ory

    keto-migrate:
        depends_on:
            - psql
        image: ory-keto:v0.6.0-alpha.3
        restart: on-failure
        command:
            migrate up --all-namespaces -c /etc/config/keto/keto.yml --yes
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
        volumes:
            -
                type: bind
                source: ./configs/keto
                target: /etc/config/keto
            -
                type: bind
                source: ./configs/keto_namespaces
                target: /keto_namespaces
        networks:
            - ory

    kratos-migrate:
        depends_on:
            - psql
        image: ory-kratos:v0.7.1-alpha.1
        restart: on-failure
        command:
            migrate -c /etc/config/kratos/kratos.yml sql -e --yes
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
            LOG_LEVEL: debug
        volumes:
            -
                type: bind
                source: ./configs/kratos
                target: /etc/config/kratos
        networks:
            - ory

    hydra:
        depends_on:
            - hydra-migrate
        image: ory-hydra:v1.10.3
        restart: unless-stopped
        command:
            serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
            OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES: public
            LOG_LEVEL: trace
        volumes:
            -
                type: bind
                source: ./configs/hydra
                target: /etc/config/hydra
        ports:
            - 4444:4444
            - 4445:4445
            - 5555:5555
        networks:
            - ory

    keto:
        depends_on:
            - keto-migrate
        image: ory-keto:v0.6.0-alpha.3
        restart: unless-stopped
        command:
            serve -c /etc/config/keto/keto.yml all
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
            LOG_LEAK_SENSITIVE_VALUES: "true"
            LOG_LEVEL: trace
            TRACING_PROVIDER: jaeger
            TRACING_SERVICE_NAME: Keto
            TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL: http://jaeger:5778/sampling
            TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS: jaeger:6831
            TRACING_PROVIDER_JAEGER_SAMPLING_TYPE: const
            TRACING_PROVIDER_JAEGER_SAMPLING_VALUE: 1
        volumes:
            -
                type: bind
                source: ./configs/keto
                target: /etc/config/keto
            -
                type: bind
                source: ./configs/keto_namespaces
                target: /keto_namespaces
        ports:
            - 4466:4466
            - 4467:4467
        networks:
            - ory

    kratos:
        depends_on:
            - kratos-migrate
        image: ory-kratos:v0.7.1-alpha.1
        restart: unless-stopped
        command: serve -c /etc/config/kratos/kratos.yml --dev
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
            LOG_LEVEL: trace
            SERVE_PUBLIC_BASE_URL: http://127.0.0.1:4455/.ory/kratos/public/ # serve through oathkeeper
        volumes:
            -
                type: bind
                source: ./configs/kratos
                target: /etc/config/kratos
        ports:
            - 4433:4433
            - 4434:4434
        networks:
            - ory

    kratos-selfservice-ui-node:
        depends_on:
            - kratos
        image: ory-kratos-selfservice-ui-node:v0.7.1-alpha.1
        environment:
            - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
            - KRATOS_PUBLIC_URL=http://kratos:4433/
            - KRATOS_ADMIN_URL=http://kratos:4434/
            - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
            - PORT=4435
            - SECURITY_MODE=jwks
        networks:
            - ory

    mailslurper:
        image: ory-mailslurper:master
        ports:
            - "4436:4436"
            - "4437:4437"
        networks:
            - ory
    
    oathkeeper:
        depends_on:
            - psql
        image: ory-oathkeeper:v0.38.14-beta.1
        restart: unless-stopped
        command: serve --config=/etc/config/oathkeeper/oathkeeper.yml
        environment:
            LOG_LEVEL: debug
            LOG_LEAK_SENSITIVE_VALUES: "true"
            TRACING_PROVIDER: jaeger
            TRACING_SERVICE_NAME: Oathkeeper
            TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL: http://jaeger:5778/sampling
            TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS: jaeger:6831
            TRACING_PROVIDER_JAEGER_SAMPLING_TYPE: const
            TRACING_PROVIDER_JAEGER_SAMPLING_VALUE: 1
        volumes:
            -
                type: bind
                source: ./configs/oathkeeper
                target: /etc/config/oathkeeper
        ports:
            - 4455:4455
            - 4456:4456
        networks:
            - ory

    jaeger:
        image: jaegertracing/all-in-one:1.22
        ports:
            - 16686:16686
        networks:
            - ory

networks:
    ory: