version: '3.7'
services:
    
    psql:
        image: postgres:13.2
        restart: unless-stopped
        environment:
            POSTGRES_USER: ory-user
            POSTGRES_PASSWORD: ory-pass
            POSTGRES_DB: ory-data
        ports:
            - 5432:5432
        #     PGDATA: /mnt/data/psql/data
        #     POSTGRES_INITDB_WALDIR: /mnt/data/psql/wal
        # volumes:
        #     -
        #         type: bind
        #         source: ./psql/data
        #         target: /mnt/data/psql/data
        #     -
        #         type: bind
        #         source: ./psql/wal
        #         target: /mnt/data/psql/wal
        networks:
            - ory

    hydra-migrate:
        depends_on:
            - psql
        image: oryd/hydra
        restart: on-failure
        command:
            migrate -c /etc/config/hydra/hydra.yml sql -e --yes
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
        volumes:
            -
                type: bind
                source: ./configs/hydra
                target: /etc/config/hydra
        networks:
            - ory

    keto-migrate:
        depends_on:
            - psql
        image: oryd/keto
        restart: on-failure
        command:
            migrate up -c /etc/config/keto/keto.yml --yes
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
        volumes:
            -
                type: bind
                source: ./configs/keto
                target: /etc/config/keto
            -
                type: bind
                source: ./configs/keto_namespaces
                target: /keto_namespaces
        networks:
            - ory

    kratos-migrate:
        depends_on:
            - psql
        image: oryd/kratos
        restart: on-failure
        command:
            migrate -c /etc/config/kratos/kratos.yml sql -e --yes
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
            LOG_LEVEL: debug
        volumes:
            -
                type: bind
                source: ./configs/kratos
                target: /etc/config/kratos
        networks:
            - ory

    hydra-login-consent-node:
        image: oryd/hydra-login-consent-node
        environment:
            PORT: 4420
            HYDRA_ADMIN_URL: http://hydra:4445
        labels:
            SERVICE_NAME: consent
            SERVICE_4420_NAME: consent
        networks:
            - ory
    hydra-consumer:
        image: oryd/hydra
        command:
            token user --port 9010 --scope openid,offline --redirect http://consumer-example.service.consul:9010/callback --no-shutdown --auth-url http://127.0.0.1:4455/oauth2/auth
            #--redirect http://127.0.0.1:9010/callback
        environment:
            OAUTH2_CLIENT_ID: another-consumer-01
            OAUTH2_CLIENT_SECRET: _XPe12Yo9iDKPlQHphtDQEFYn2
            HYDRA_URL: http://oathkeeper.service.consul:4455
        ports:
          - "9010"
        labels:
            SERVICE_NAME: consumer-example
            SERVICE_9010_NAME: consumer-example
        networks:
            - ory
        
    hydra:
        depends_on:
            - hydra-migrate
        image: oryd/hydra
        restart: unless-stopped
        command:
            serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http --dangerous-allow-insecure-redirect-urls http://consumer-example.service.consul:9010/callback
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
            OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES: public
            LOG_LEVEL: trace
            LOG_LEAK_SENSITIVE_VALUES: "true"
        volumes:
            -
                type: bind
                source: ./configs/hydra
                target: /etc/config/hydra
        ports:
            - 4444:4444
            - 4445:4445
            - 5555:5555
        labels:
            SERVICE_NAME: hydra
            SERVICE_4444_NAME: hydra
            SERVICE_4445_NAME: hydra-admin
        networks:
            - ory

    keto:
        depends_on:
            - keto-migrate
        image: oryd/keto
        restart: unless-stopped
        command:
            serve -c /etc/config/keto/keto.yml all
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
            LOG_LEAK_SENSITIVE_VALUES: "true"
            LOG_LEVEL: trace
            TRACING_PROVIDER: jaeger
            TRACING_SERVICE_NAME: Keto
            TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL: http://jaeger:5778/sampling
            TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS: jaeger:6831
            TRACING_PROVIDER_JAEGER_SAMPLING_TYPE: const
            TRACING_PROVIDER_JAEGER_SAMPLING_VALUE: 1
        volumes:
            -
                type: bind
                source: ./configs/keto
                target: /etc/config/keto
            -
                type: bind
                source: ./configs/keto_namespaces
                target: /keto_namespaces
        ports:
            - 4466:4466
            - 4467:4467
        networks:
            - ory

    kratos:
        depends_on:
            - kratos-migrate
        image: oryd/kratos
        restart: unless-stopped
        command: serve -c /etc/config/kratos/kratos.yml --dev
        environment:
            DSN: postgres://ory-user:ory-pass@psql:5432/ory-data?sslmode=disable&max_conns=20&max_idle_conns=4
            LOG_LEVEL: trace
            LOG_LEAK_SENSITIVE_VALUES: "true"
            SERVE_PUBLIC_BASE_URL: http://127.0.0.1:4455/.ory/kratos/public/ # serve through oathkeeper
        volumes:
            -
                type: bind
                source: ./configs/kratos
                target: /etc/config/kratos
        ports:
            - 4433:4433
            - 4434:4434
        labels:
          SERVICE_NAME: kratos
          SERVICE_4433_NAME: kratos
          SERVICE_4434_NAME: kratos-admin
        networks:
            - ory

    kratos-selfservice-ui-node:
        depends_on:
            - kratos
        build: ../../kratos-selfservice-ui-node
        image: kratos-selfservice-ui-node:hydra-integration-2021
        environment:
            - JWKS_URL=http://oathkeeper-api.service.consul:4456/.well-known/jwks.json
            - KRATOS_PUBLIC_URL=http://kratos.service.consul:4433/
            # http://127.0.0.1:4433/
            # http://127.0.0.1:4455/.ory/kratos/public/
            #http://kratos.service.consul:4433/
            - KRATOS_ADMIN_URL=http://kratos-admin.service.consul:4434/
            - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
            - HYDRA_ADMIN_URL=http://hydra-admin.service.consul:4445/
            - PORT=4435
            #- SECURITY_MODE=jwt
            - SECURITY_MODE=cookie
            - HYDRA_COOKIE_SECRET=PLEASE-CHANGE-ME-AGAIN
        networks:
            - ory
        labels:
          SERVICE_NAME: kratos-selfservice-ui-node
          SERVICE_4435_NAME: kratos-selfservice-ui-node

    mailslurper:
        image: oryd/mailslurper:smtps-latest
        ports:
            - "4436:4436"
            - "4437:4437"
        labels:
            SERVICE_NAME: mailslurper
            SERVICE_4436_NAME: mailslurper
            SERVICE_1025_NAME: mailslurper
        networks:
            - ory
    
    oathkeeper:
        depends_on:
            - psql
        image: oryd/oathkeeper
        restart: unless-stopped
        command: serve --config=/etc/config/oathkeeper/oathkeeper.yml
        environment:
            LOG_LEVEL: debug
            LOG_LEAK_SENSITIVE_VALUES: "true"
            TRACING_PROVIDER: jaeger
            TRACING_SERVICE_NAME: Oathkeeper
            TRACING_PROVIDER_JAEGER_SAMPLING_SERVER_URL: http://jaeger:5778/sampling
            TRACING_PROVIDER_JAEGER_LOCAL_AGENT_ADDRESS: jaeger:6831
            TRACING_PROVIDER_JAEGER_SAMPLING_TYPE: const
            TRACING_PROVIDER_JAEGER_SAMPLING_VALUE: 1
        volumes:
            -
                type: bind
                source: ./configs/oathkeeper
                target: /etc/config/oathkeeper
        ports:
            - 4455:4455
            - 4456:4456
        labels:
            SERVICE_NAME: oathkeeper
            SERVICE_4455_NAME: oathkeeper
            SERVICE_4456_NAME: oathkeeper-api
        networks:
            - ory

    jaeger:
        image: jaegertracing/all-in-one:1.22
        ports:
            - 16686:16686
        networks:
            - ory

networks:
    ory:
