serve:
    cookies:
        same_site_mode: Lax
  
urls:
    self:
        issuer: http://127.0.0.1:4444
    consent: http://kratos-selfservice-ui-node.service.consul:4435/auth/consent
    login: http://kratos-selfservice-ui-node.service.consul:4435/auth/login
    logout: http://kratos-selfservice-ui-node.service.consul:4435/auth/logout
    #consent: http://consent.service.consul:4420/consent
    #login: http://consent.service.consul:4420/login
    #logout: http://consent.service.consul:4420/logout
  
secrets:
    system:
    - youReallyNeedToChangeThis

strategies:
    access_token: jwt
  
oidc:
    subject_identifiers:
        supported_types:
        - pairwise
        - public
        pairwise:
            salt: youReallyNeedToChangeThis

tracing:
    provider: jaeger
    service_name: Hydra
    providers:
        jaeger:
            local_agent_address: jaeger:6831
            sampling:
                type: const
                value: 1
                server_url: http://jaeger:5778/sampling
